# Generated by Django 5.2.13 on 2026-04-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100)),
                ('planting_date', models.DateField()),
                ('stage', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready'), ('harvested', 'Harvested')], default='planted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Field Agent')], max_length=20)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready'), ('harvested', 'Harvested')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='Seasons.field')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='Seasons.user')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='Seasons.user'),
        ),
    ]
